# 4. Limpieza de los datos

## 4.1 Datos perdidos

In [32]:
df_modelo.apply(lambda x: x.isna().sum()/df_modelo.shape[0]*100)

cod_mun                        0.000000
año                            0.000000
NOMBRE                         0.015623
analfabetismo                  0.015623
bajo_logro_educativo           0.015623
barreras_primera_infancia      0.015623
barreras_acceso_salud          0.015623
tasa_dependencia               0.015623
hacinamiento_critico           0.015623
inadec_eliminacion_excretas    0.015623
inasistencia_escolar           0.015623
inadec_paredes                 0.015623
inadec_pisos                   0.015623
rezago_escolar                 0.015623
sin_agua_mejorada              0.015623
sin_aseguramiento_salud        0.015623
trabajo_infantil               0.015623
trabajo_informal               0.015623
longitud                       0.015623
latitud                        0.015623
tasa_x1000                     0.000000
casos_totales                  0.000000
riesgo                         0.000000
Código Entidad                 1.202937
Año                            1.202937
Componente de gestión          1.202937
Componente de resultados       1.202937
MDM                            1.202937
dtype: float64

In [33]:
#Proporción de missings por observación (como una nueva columna del dataset)
df_modelo['n_missings'] = df_modelo.apply(lambda x: x.isna().sum(),axis=1)

# Valoramos distribución
df_modelo.n_missings.describe()

count    6401.000000
mean        0.062959
std         0.612835
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        23.000000
Name: n_missings, dtype: float64

Se decide eliminar lo valores perdidos ya que su incidencia no es mucha

In [34]:
df_modelo = df_modelo.dropna()

## 4.2 Tipo de Variables

In [35]:
df_modelo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6324 entries, 0 to 6400
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   cod_mun                      6324 non-null   object
 1   año                          6324 non-null   object
 2   NOMBRE                       6324 non-null   object
 3   analfabetismo                6324 non-null   float64
 4   bajo_logro_educativo         6324 non-null   float64
 5   barreras_primera_infancia    6324 non-null   float64
 6   barreras_acceso_salud        6324 non-null   float64
 7   tasa_dependencia             6324 non-null   float64
 8   hacinamiento_critico         6324 non-null   float64
 9   inadec_eliminacion_excretas  6324 non-null   float64
 10  inasistencia_escolar         6324 non-null   float64
 11  inadec_paredes               6324 non-null   float64
 12  inadec_pisos                 6324 non-null   float64
 13  rezago_escolar               6324 non-null   float64
 14  sin_agua_mejorada            6324 non-null   float64
 15  sin_aseguramiento_salud      6324 non-null   float64
 16  trabajo_infantil             6324 non-null   float64
 17  trabajo_informal             6324 non-null   float64
 18  longitud                     6324 non-null   float64
 19  latitud                      6324 non-null   float64
 20  tasa_x1000                   6324 non-null   float64
 21  casos_totales                6324 non-null   int64
 22  riesgo                       6324 non-null   category
 23  Código Entidad               6324 non-null   object
 24  Año                          6324 non-null   float64
 25  Componente de gestión        6324 non-null   float64
 26  Componente de resultados     6324 non-null   float64
 27  MDM                          6324 non-null   float64
 28  n_missings                   6324 non-null   int64
dtypes: category(1), float64(22), int64(2), object(4)
memory usage: 1.4+ MB